server:
  port: 9001

security:
  jwt:
    key-store: classpath:mytest.jks
    key-store-password: mypass
    key-pair-alias: mytest
    key-pair-password: mypass

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ds_0?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true
